spring:
  application:
    name: SWKROA
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/swkroadb
    username: swkroaadmin
    password: cagst23824
    hikari:
      maximum-pool-size: 10

logging:
  level:
    root: info
