ALTER TABLE address
  MODIFY COLUMN address_type_cd BIGINT UNSIGNED NULL;

ALTER TABLE email
  MODIFY COLUMN email_type_cd BIGINT UNSIGNED NULL;

ALTER TABLE phone
  MODIFY COLUMN phone_type_cd BIGINT UNSIGNED NULL;
