INSERT INTO country (country_code, country_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'Spain', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);

INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'C', 'A Coruña', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'VI', 'Álava', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'AB', 'Albacete', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'A', 'Alicante', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'AL', 'Almería', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'O', 'Asturias', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'AV', 'Ávila', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'BA', 'Badajoz', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'PM', 'Balears', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'B', 'Barcelona', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'BU', 'Burgos', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'CC', 'Cáceres', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'CA', 'Cádiz', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'S', 'Cantabria', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'CS', 'Castellón', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'CR', 'Ciudad Real', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'CO', 'Córdoba', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'CU', 'Cuenca', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'GI', 'Girona', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'GR', 'Granada', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'GU', 'Guadalajara', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'SS', 'Gipuzkoa', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'H', 'Huelva', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'HU', 'Huesca', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'J', 'Jaén', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'LO', 'La Rioja', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'GC', 'Las Palmas', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'LE', 'León', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'L', 'Lleida', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'LU', 'Lugo', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'M', 'Madrid', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'MA', 'Málaga', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'MU', 'Murcia', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'NA', 'Navarra', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'OR', 'Ourense', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'P', 'Palencia', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'PO', 'Pontevedra', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'SA', 'Salamanca', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'TF', 'Santa Cruz de Tenerife', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'SG', 'Segovia', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'SE', 'Sevilla', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'SO', 'Soria', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'T', 'Tarragona', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'TE', 'Teruel', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'TO', 'Toledo', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'V', 'Valencia', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'VA', 'Valladolid', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'BI', 'Bizkaia', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'ZA', 'Zamora', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
INSERT INTO state (country_code, state_code, state_name, create_dt_tm, create_id, updt_dt_tm, updt_id) VALUES ('ES', 'Z', 'Zaragoza', CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 0);
